package com.autonomous.devops_orchestrator.controller;

import com.autonomous.devops_orchestrator.model.AnalysisResponse;
import com.autonomous.devops_orchestrator.service.AiServiceClient;
import com.autonomous.devops_orchestrator.service.CommandExecutionService;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/orchestrator")
public class OrchestratorController {

    private final AiServiceClient aiServiceClient;
    private final CommandExecutionService executionService;

    // Inject both services
    public OrchestratorController(AiServiceClient aiServiceClient, CommandExecutionService executionService) {
        this.aiServiceClient = aiServiceClient;
        this.executionService = executionService;
    }

    @PostMapping("/diagnose")
    public AnalysisResponse diagnoseLog(@RequestBody String rawLog) {
        System.out.println("--- [Java Orchestrator] Intercepted system error log ---");

        // 1. Get diagnosis from Python -> Gemini pipeline
        AnalysisResponse response = aiServiceClient.sendLogToAi(rawLog);

        System.out.println("--- [Java Orchestrator] Analysis received. Triggering Auto-Remediation Engine ---");

        // 2. Automatically execute the corrective actions generated by the AI
        executionService.executeMitigationCommands(response.getCommands_to_execute());

        return response;
    }
}